/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class pnl_Reportes extends javax.swing.JPanel {

    /**
     * Creates new form pnl_Reportes
     */
    public pnl_Reportes() {
        initComponents();
        GenerarTablaRepo();
        configurarInicio();
    }

    private void configurarInicio() {
        // 1) combos
        cargarOpcionesCampo();

        // 2) tabla: que no se edite
        tabla_reportes.setDefaultEditor(Object.class, null);
        tabla_reportes.setRowHeight(26);

        // 3) listeners
        cb_campo.addActionListener(e -> onCampoChange());
        btn_buscar.addActionListener(e -> buscarFacturas());
        btn_limpiar.addActionListener(e -> limpiarFiltros());
        btn_excel.addActionListener(e -> exportarExcel());
        btn_pdf.addActionListener(e -> exportarPDF());

        // Enter en el txt para buscar
        txt_busqueda.addActionListener(e -> buscarFacturas());

        // 4) estado inicial
        onCampoChange();
        limpiarFiltros();
    }

    private DefaultTableModel modeloRepo;

    private void GenerarTablaRepo() {
        String[] titulos = {
            "N° Factura", "Fecha", "Cédula", "Subtotal", "Descuento", "IVA", "Total", "Usuario", "Habitación"
        };
        modeloRepo = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        tabla_reportes.setModel(modeloRepo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        card_totalVentas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_tv_value = new javax.swing.JLabel();
        card_totalFacturas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_tf_value = new javax.swing.JLabel();
        card_habTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_hab_value = new javax.swing.JLabel();
        card_userTop = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_usr_value = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_valor = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        dp_fin = new org.jdesktop.swingx.JXDatePicker();
        txt_busqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        dp_inicio = new org.jdesktop.swingx.JXDatePicker();
        cb_campo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbl_bsqdTexto1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_excel = new javax.swing.JButton();
        btn_pdf = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_reportes = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card_totalVentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        card_totalVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Total Ventas");
        card_totalVentas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lbl_tv_value.setText("jLabel5");
        card_totalVentas.add(lbl_tv_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jPanel2.add(card_totalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 110));

        card_totalFacturas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Total Facturas");

        lbl_tf_value.setText("jLabel8");

        javax.swing.GroupLayout card_totalFacturasLayout = new javax.swing.GroupLayout(card_totalFacturas);
        card_totalFacturas.setLayout(card_totalFacturasLayout);
        card_totalFacturasLayout.setHorizontalGroup(
            card_totalFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_totalFacturasLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
            .addGroup(card_totalFacturasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbl_tf_value)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card_totalFacturasLayout.setVerticalGroup(
            card_totalFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_totalFacturasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(lbl_tf_value)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.add(card_totalFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 140, 110));

        card_habTop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Mejor Habitacion");

        lbl_hab_value.setText("jLabel9");

        javax.swing.GroupLayout card_habTopLayout = new javax.swing.GroupLayout(card_habTop);
        card_habTop.setLayout(card_habTopLayout);
        card_habTopLayout.setHorizontalGroup(
            card_habTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_habTopLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_habTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_hab_value)
                .addGap(53, 53, 53))
        );
        card_habTopLayout.setVerticalGroup(
            card_habTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_habTopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lbl_hab_value)
                .addGap(27, 27, 27))
        );

        jPanel2.add(card_habTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 150, 110));

        card_userTop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Mejor Vendedor");

        lbl_usr_value.setText("jLabel10");

        javax.swing.GroupLayout card_userTopLayout = new javax.swing.GroupLayout(card_userTop);
        card_userTop.setLayout(card_userTopLayout);
        card_userTopLayout.setHorizontalGroup(
            card_userTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_userTopLayout.createSequentialGroup()
                .addGroup(card_userTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_userTopLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addGroup(card_userTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_usr_value)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        card_userTopLayout.setVerticalGroup(
            card_userTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_userTopLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lbl_usr_value)
                .addGap(28, 28, 28))
        );

        jPanel2.add(card_userTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 140, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 890, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_valor.setText("Tipo Busqueda");
        jPanel3.add(lbl_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, 40));
        jPanel3.add(dp_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        txt_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busquedaActionPerformed(evt);
            }
        });
        jPanel3.add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 132, -1));

        jLabel7.setText("Fecha FIn");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 40));
        jPanel3.add(dp_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        cb_campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Usuario", "Cliente", "N factura", "Habitacion" }));
        cb_campo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_campoActionPerformed(evt);
            }
        });
        jPanel3.add(cb_campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel3.setText("Fecha Inicio");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lbl_bsqdTexto1.setText("Busqueda por texto");
        jPanel3.add(lbl_bsqdTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 320, 480));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_excel.setText("Exportar a Execel");
        jPanel4.add(btn_excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        btn_pdf.setText("Exportar a PDF");
        jPanel4.add(btn_pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        tabla_reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabla_reportes);

        jScrollPane3.setViewportView(jScrollPane4);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 415));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 560, 480));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -10, 930, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void cb_campoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_campoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_campoActionPerformed

    private void cargarOpcionesCampo() {
        cb_campo.removeAllItems();
        cb_campo.addItem("Todos");
        cb_campo.addItem("Usuario");
        cb_campo.addItem("Cliente (Cédula)");
        cb_campo.addItem("N° Factura");
        cb_campo.addItem("Habitación");
    }

    private void buscarFacturas() {
    try {
        String campo = (cb_campo.getSelectedItem() == null) ? "Todos" : cb_campo.getSelectedItem().toString();
        String texto = (txt_busqueda.getText() == null) ? "" : txt_busqueda.getText().trim();
        java.util.Date dIni = dp_inicio.getDate();
        java.util.Date dFin = dp_fin.getDate();

        String where = buildWhere(campo, texto, dIni, dFin);

        String sql =
            "SELECT " +
            " cf.num_fac  AS 'N° Factura', " +
            " cf.fec_fac  AS 'Fecha', " +
            " cf.ced_cli  AS 'Cédula', " +
            " cf.sub_fac  AS 'Subtotal', " +
            " cf.desc_fac AS 'Descuento', " +
            " cf.iva_fac  AS 'IVA', " +
            " cf.tot_fac  AS 'Total', " +
            " u.nom_usu   AS 'Usuario', " +
            " h.cod_hab   AS 'Habitación' " +
            "FROM cabecera_factura cf " +
            "LEFT JOIN usuarios u ON cf.id_usuario = u.id_usu " +
            "LEFT JOIN habitaciones h ON cf.id_hab = h.id_hab " +
            where +
            " ORDER BY cf.fec_fac DESC, cf.num_fac DESC;";

        Clases.cls_conexion cnx = new Clases.cls_conexion();
        cnx.CargarTabla(sql, tabla_reportes);

        // cards
        actualizarCards(where);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error al buscar facturas", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private String buildWhere(String campo, String texto, java.util.Date dIni, java.util.Date dFin) {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String t = (texto == null) ? "" : texto.trim();
    t = t.replace("'", "''"); // evita romper SQL

    StringBuilder where = new StringBuilder(" WHERE 1=1 ");

    // Fechas
    if (dIni != null) where.append(" AND DATE(cf.fec_fac) >= '").append(sdf.format(dIni)).append("' ");
    if (dFin != null) where.append(" AND DATE(cf.fec_fac) <= '").append(sdf.format(dFin)).append("' ");

    if (t.isEmpty()) return where.toString();

    // Normaliza "H8" a "8"
    String habNumero = null;
    if (t.matches("(?i)h\\d+")) {
        habNumero = t.substring(1); // quita H
    }

    // Filtros
    switch (campo) {
        case "Usuario" -> where.append(" AND u.nom_usu LIKE '%").append(t).append("%' ");
        case "Cliente (Cédula)" -> where.append(" AND cf.ced_cli LIKE '%").append(t).append("%' ");
        case "N° Factura" -> where.append(" AND CAST(cf.num_fac AS CHAR) LIKE '%").append(t).append("%' ");
        case "Habitación" -> {
            String v = (habNumero != null) ? habNumero : t;
            where.append(" AND (CAST(cf.id_hab AS CHAR) LIKE '%").append(v).append("%' OR h.cod_hab LIKE '%").append(t).append("%') ");
        }
        default -> {
            // TODOS: usuario / cédula / num factura / habitación (id o H#)
            where.append(" AND (")
                 .append(" u.nom_usu LIKE '%").append(t).append("%' ")
                 .append(" OR cf.ced_cli LIKE '%").append(t).append("%' ")
                 .append(" OR CAST(cf.num_fac AS CHAR) LIKE '%").append(t).append("%' ")
                 .append(" OR CAST(cf.id_hab AS CHAR) LIKE '%").append((habNumero != null ? habNumero : t)).append("%' ")
                 .append(" OR h.cod_hab LIKE '%").append(t).append("%' ")
                 .append(" ) ");
        }
    }

    return where.toString();
}
    
    private void actualizarCards(String where) {
    try {
        Clases.cls_conexion cnx = new Clases.cls_conexion();

        // 1) Total ventas + total facturas
        String sqlTotales =
            "SELECT COUNT(*) AS n, IFNULL(SUM(cf.tot_fac),0) AS total " +
            "FROM cabecera_factura cf " +
            "LEFT JOIN usuarios u ON cf.id_usuario = u.id_usu " +
            "LEFT JOIN habitaciones h ON cf.id_hab = h.id_hab " +
            where + ";";

        java.sql.ResultSet rs = cnx.Consulta(sqlTotales);
        int n = 0;
        double total = 0;
        if (rs != null && rs.next()) {
            n = rs.getInt("n");
            total = rs.getDouble("total");
        }
        if (rs != null) rs.close();

        lbl_tv_value.setText(String.format(java.util.Locale.US, "$ %.2f", total));
        lbl_tf_value.setText(String.valueOf(n));

        // 2) Habitación más usada (por cantidad)
        String sqlHabTop =
            "SELECT IFNULL(h.cod_hab, CONCAT('Hab ', cf.id_hab)) AS hab, COUNT(*) AS c " +
            "FROM cabecera_factura cf " +
            "LEFT JOIN habitaciones h ON cf.id_hab = h.id_hab " +
            "LEFT JOIN usuarios u ON cf.id_usuario = u.id_usu " +
            where +
            " GROUP BY hab ORDER BY c DESC LIMIT 1;";

        rs = cnx.Consulta(sqlHabTop);
        if (rs != null && rs.next()) {
            lbl_hab_value.setText(rs.getString("hab") + " (" + rs.getInt("c") + ")");
        } else {
            lbl_hab_value.setText("-");
        }
        if (rs != null) rs.close();

        // 3) Usuario con más ventas (por dinero)
        String sqlUsuTop =
            "SELECT IFNULL(u.nom_usu,'(Sin usuario)') AS usu, IFNULL(SUM(cf.tot_fac),0) AS t " +
            "FROM cabecera_factura cf " +
            "LEFT JOIN usuarios u ON cf.id_usuario = u.id_usu " +
            "LEFT JOIN habitaciones h ON cf.id_hab = h.id_hab " +
            where +
            " GROUP BY usu ORDER BY t DESC LIMIT 1;";

        rs = cnx.Consulta(sqlUsuTop);
        if (rs != null && rs.next()) {
            lbl_usr_value.setText(rs.getString("usu") + " ($" + String.format(java.util.Locale.US,"%.2f", rs.getDouble("t")) + ")");
        } else {
            lbl_usr_value.setText("-");
        }
        if (rs != null) rs.close();

    } catch (Exception e) {
        // No revientes el panel por fallar cards
        lbl_tv_value.setText("-");
        lbl_tf_value.setText("-");
        lbl_hab_value.setText("-");
        lbl_usr_value.setText("-");
    }
}




    private void onCampoChange() {
        String campo = (cb_campo.getSelectedItem() == null) ? "Todos" : cb_campo.getSelectedItem().toString();
        // Siempre permitimos escribir, porque en "Todos" buscas global
        txt_busqueda.setEnabled(true);
        txt_busqueda.setToolTipText("Busca por Usuario / Cédula / N° Factura / Habitación (ej: H8 o 8)");


        // Placeholder visual simple
        if (campo.equalsIgnoreCase("Todos")) {
            txt_busqueda.setToolTipText("Busca por Usuario / Cédula / N° Factura / Habitación (ej: H8 o 8)");
        } else {
            txt_busqueda.setToolTipText("Filtro por: " + campo);
        }
    }

    
    private void limpiarFiltros() {
    // Reset filtro principal
    if (cb_campo.getItemCount() > 0) {
        cb_campo.setSelectedIndex(0); // "Todos"
    }

    // Reset texto de búsqueda
    txt_busqueda.setText("");
    txt_busqueda.setEnabled(true);
    lbl_valor.setText("Filtro: Todos");

    // Reset fechas
    dp_inicio.setDate(null);
    dp_fin.setDate(null);

    // Ejecuta búsqueda limpia
    buscarFacturas();

}


    private void exportarExcel() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Guardar reporte como Excel (CSV)");
        chooser.setSelectedFile(new java.io.File("reporte_ventas.csv"));

        int result = chooser.showSaveDialog(this);
        if (result != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File file = chooser.getSelectedFile();

        try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(file))) {

            for (int col = 0; col < tabla_reportes.getColumnCount(); col++) {
                bw.write(tabla_reportes.getColumnName(col));
                if (col < tabla_reportes.getColumnCount() - 1) {
                    bw.write(";");
                }
            }
            bw.newLine();

            for (int row = 0; row < tabla_reportes.getRowCount(); row++) {
                for (int col = 0; col < tabla_reportes.getColumnCount(); col++) {
                    Object valor = tabla_reportes.getValueAt(row, col);
                    bw.write(valor == null ? "" : valor.toString());
                    if (col < tabla_reportes.getColumnCount() - 1) {
                        bw.write(";");
                    }
                }
                bw.newLine();
            }

            bw.flush();

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo guardado correctamente.\nPuedes abrirlo con Excel.",
                    "Exportar a Excel",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error al exportar a Excel",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void exportarPDF() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Guardar reporte como PDF");
        chooser.setSelectedFile(new java.io.File("reporte_ventas.pdf"));

        int result = chooser.showSaveDialog(this);
        if (result != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File file = chooser.getSelectedFile();

        try {

            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(doc, new java.io.FileOutputStream(file));
            doc.open();

            doc.add(new com.itextpdf.text.Paragraph("Reporte de Ventas - StayBill"));
            doc.add(new com.itextpdf.text.Paragraph(" "));

            com.itextpdf.text.pdf.PdfPTable table
                    = new com.itextpdf.text.pdf.PdfPTable(tabla_reportes.getColumnCount());

            for (int col = 0; col < tabla_reportes.getColumnCount(); col++) {
                table.addCell(new com.itextpdf.text.Phrase(tabla_reportes.getColumnName(col)));
            }

            for (int row = 0; row < tabla_reportes.getRowCount(); row++) {
                for (int col = 0; col < tabla_reportes.getColumnCount(); col++) {
                    Object valor = tabla_reportes.getValueAt(row, col);
                    table.addCell(new com.itextpdf.text.Phrase(
                            valor == null ? "" : valor.toString()
                    ));
                }
            }

            doc.add(table);
            doc.close();

            JOptionPane.showMessageDialog(
                    this,
                    "PDF generado correctamente.",
                    "Exportar a PDF",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error al exportar a PDF",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_excel;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JPanel card_habTop;
    private javax.swing.JPanel card_totalFacturas;
    private javax.swing.JPanel card_totalVentas;
    private javax.swing.JPanel card_userTop;
    private javax.swing.JComboBox<String> cb_campo;
    private org.jdesktop.swingx.JXDatePicker dp_fin;
    private org.jdesktop.swingx.JXDatePicker dp_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_bsqdTexto1;
    private javax.swing.JLabel lbl_hab_value;
    private javax.swing.JLabel lbl_tf_value;
    private javax.swing.JLabel lbl_tv_value;
    private javax.swing.JLabel lbl_usr_value;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JTable tabla_reportes;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
